server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    druid:
      username: root
      password: 123456
      url: jdbc:mysql://127.0.0.1:3306/cloud2020?useUnicode=true&serverTimezone=GMT%2B8&useSSL=false
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.suave.cloud.entity
  configuration:
    map-underscore-to-camel-case: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka